def generate_recipe():
	recipies = {}
	recipies['Strength'] = ['Beast Limb','Plant Branch','Chunk of Graphite']
	recipies['Health'] = ['Yellow Pollen','Plant Leaf','Golden Apple']
	recipies['Coordination'] = ['Animal Eye','Dragon Eye','Serpent Eye']
	recipies['Agility'] = ['Animal Tongue','Beast Wing','Serpent Tongue']
	recipies['Retaliation'] = ['Humanoid Bone','Serpent Tail']
	recipies['Restoration'] = ['Humanoid Flesh','Plant Root']
	recipies['Dueling'] = ['Animal Tooth','Beast Tooth']
	recipies['Sniping'] = ['Plant Vine','Squid Tentacle']
	recipies['Sorcery'] = ['Elemental Energy','Magical Stone']
	recipies['Brawling'] = ['Aberration Mind Source','Protection Stone']
	recipies['Elusion'] = ['Octopus Ink','Ooze Gel']
	recipies['Normalizing'] = ['Aberration Mind Source','Construct Power']
	recipies['Hunting'] = ['Animal Eye','Animal Tooth','Animal Tongue','Animal Wing']
	recipies['Taming'] = ['Beast Fur','Beast Limb','Beast Tooth','Beast Wing']
	recipies['Destruction'] = ['Construct Power','Chunk of Graphite','Rainbow Shard','Honeycomb']
	recipies['Slaying'] = ['Dragon Eye', 'Dragon Scale','Dragon Tail']
	recipies['Weathering'] = ['Elemental Energy', 'Plant Root', 'Beast Wing']
	recipies['Murdering'] = ['Humanoid Bone', 'Humanoid Flesh', 'Humanoid Limb']
	recipies['Solidifying'] = ['Ooze Gel', 'Yellow Pollen','Copper Ore']
	recipies['Weedwhacking'] = ['Plant Branch', 'Plant Leaf', 'Plant Root', 'Plant Vine']
	recipies['Charming'] = ['Serpent Eye', 'Serpent Tail', 'Serpent Tongue']
	recipies['Exterminating'] = ['Vermin Eye', 'Vermin Tooth', 'Bird Nest']
	recipies['Swiftness'] = ['Octopus Ink','Vermin Eye']
	recipies['Potency'] = ['Lucky Coin', 'Dragon Scale']
	recipies['Recklessness'] = ['Construct Power', 'Serpent Tongue']
	recipies['Resilience'] = ['Turtle Shell','Protection Stone']
	recipies['Retribution'] = ['Fish Fin', 'Chunk of Graphite']
	recipies['Recovery'] = ['Plant Vine','Rune Stone']
	recipies['Smithing'] = ['Chunk of Coal','Humanoid Limb']
	recipies['Etching'] = ['Turtle Shell', 'Fish Fin']
	recipies['Harvesting'] = ['Squid Tentacle','Honeycomb', 'Chunk of Coal','Magical Stone']
	recipies['Wisdom'] = ['Aberration Mind Source', 'Vermin Tooth']
	recipies['Greed'] = ['Copper Ore', 'Dragon Tail']
	recipies['Luck'] = ['Lucky Coin', 'Ooze Gel']
	recipies['Mastery'] = ['Elemental Energy', 'Bird Nest']
	recipies['Endurance'] = ['Beast Fur', 'Golden Apple']
	recipies['Celerity'] = ['Animal Eye', 'Squid Tentacle', 'Magical Stone']
	recipies['Piercing'] = ['Serpent Tail', 'Animal Tooth', 'Yellow Pollen']
	recipies['Chronokinesis'] = ['Rainbow Shard', 'Animal Wing', 'Rune Stone']
	
	return(recipies)

